### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Dalan94** [spantaleev/sftpman-gtk#6]
When I start sftpman-gtk on my manjaro, I have this error:
```
Traceback (most recent call last):
  File "/usr/bin/sftpman-gtk", line 11, in <module>
    load_entry_point('sftpman-gtk==1.0.0', 'console_scripts', 'sftpman-gtk')()
  File "/usr/lib/python3.6/site-packages/sftpman_gtk/launcher.py", line 9, in main
    gui.start()
  File "/usr/lib/python3.6/site-packages/sftpman_gtk/gui.py", line 539, in start
    obj = SftpManGtk()
  File "/usr/lib/python3.6/site-packages/sftpman_gtk/gui.py", line 252, in __init__
    self.list_container_wrapper.add_with_viewport(self._create_list_container())
  File "/usr/lib/python3.6/site-packages/sftpman_gtk/gui.py", line 224, in _create_list_container
    self.refresh_list()
  File "/usr/lib/python3.6/site-packages/sftpman_gtk/gui.py", line 173, in refresh_list
    self.list_container.pack_start(label, True, True, 0)
AttributeError: 'ListBox' object has no attribute 'pack_start'
```

The last time I used it (maybe 2 month ago) there were no problem.

**Comment by spantaleev** [comment]
Thanks for the report!

It was a regression since 39ced4d105f7 which only occurred when the list of sftp filesystems is empty.
Version `1.0.1` of `sftpman-gtk` is out and corrects the problem.

------

By the way, since you say that you've used the program before, I guess you'd already defined some filesystems though. You're probably wondering why the list of filesystems would be empty for you.

It's because from `sftpman=1.0.0` onwards the configuration is stored in `~/.config/sftpman/mounts` as `.json` files (used to be `.js` files).

You'd need to relocate your configuration files (rename from `.js` to `.json`) and it would work.
To easily do it, you can run:
```bash
for f in $(ls ~/.config/sftpman/mounts/*.js); do n=$(echo $f | sed 's/.js$/.json/'); mv $f $n; done;
```

During an upgrade from `sftpman < 1.0` to `sftpman > 1.0` it's supposed to tell you about this and how to do the migration (the command above). If you're not paying attention or are using some GUI to do AUR updates, you probably missed it though.
